apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    my-key: value
spec:
  template:
    metadata:
      name: httpd-pod
      labels:
        tier: frontend
    spec:
      containers:
        - name: httpd-frontend-container
          image: httpd:2.4-alpine
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
