apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    xyz: xyz
spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        app: FE
    spec:
      containers:
        - name: fe-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: FE
