apiVersion: v1
kind: Pod
metadata:
  name: mera-secret-pod
spec:
  containers:
    - name: laude-ka
      image: nginx
      volumeMounts:
        - name: secret-vol
          mountPath: /mnt/
  volumes:
    - name: secret-vol
      secret:
        secretName: m-sec 