apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: my-scheduler-1
    plugins:
      queueSort:
        enabled:
          - name: PrioritySort
          - name: CustomQueueSort
        disabled:
          - name: FairSort
      filter:
        enabled:
          - name: NodeResourceFit
          - name: TaintsToleration
        disabled:
          - name: NodeName
      score:
        enabled:
          - name: ImageLocality
          - name: MostAllocated
        disabled:
          - name: NodeResourceLeastAllocated
      bind:
        enabled:
          - name: DefaultBinder
  - schedulerName: my-scheduler-2
    plugins:
      prescore:
        disabled:
          - name: "*"
      score:
        enabled:
          - name: ImageLocality
leaderElection:
  leaderElect: false
  resourceNamespace: kube-system
