apiVersion: v1
kind: Service
metadata:
  name: frontend-np-svc
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30080
  selector:
    app: FE #label of the pods for which svc is created