apiVersion: apps/v1
kind: DaemonSet
metadata: 
   name: elasticsearch
   namespace: kube-system
spec:
  template:
    metadata: 
      name: ds-pod
      labels:
        purpose: monitoring
    spec:
      containers:
      - name: ds-cont
        image: registry.k8s.io/fluentd-elasticsearch:1.20
  selector: 
    matchLabels:
      purpose: monitoring