apiVersion: v1
kind: Pod
metadata:
  name: elephant
spec:
  containers:
  - name: ele-pod
    image: polinux/stress
    resources:
      requests:
        cpu: 500m
        memory: 10Mi
      limits:
        cpu: 1500m
        memory: 20Mi